# Run with `REST Client` extension for VS Code

@baseUrl = http://localhost:5000/api/v1
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9
@refreshToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9

### ============================================
### HEALTH CHECK
### ============================================

### Home
GET http://localhost:5000

### Health Check
GET {{baseUrl}}/health

### ============================================
### AUTH ENDPOINTS
### ============================================

### Register
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
  "firstName": "John",
  "lastName": "Doe",
  "email": "apitest@tensi.org",
  "password": "Password1#"
}

### Resend Verification Code
POST {{baseUrl}}/auth/resend-verification-code
Content-Type: application/json

{
  "email": "apitest@tensi.org"
}

### Verify Email
POST {{baseUrl}}/auth/verify-email
Content-Type: application/json

{
  "email": "apitest@tensi.org",
  "code": "942176"
}

### Login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "apitest@tensi.org",
  "password": "Password1#"
}

### Refresh Token
POST {{baseUrl}}/auth/refresh-token
Content-Type: application/json

{
  "refreshToken": "{{refreshToken}}"
}

### Logout
POST {{baseUrl}}/auth/logout
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "refreshToken": "{{refreshToken}}"
}

### Forgot Password
POST {{baseUrl}}/auth/forgot-password
Content-Type: application/json

{
  "email": "john@example.com"
}

### Resend Forgot Password
POST {{baseUrl}}/auth/resend-forgot-password
Content-Type: application/json

{
  "email": "john@example.com"
}

### Reset Password
POST {{baseUrl}}/auth/reset-password
Content-Type: application/json

{
  "token": "your_reset_token_from_email",
  "newPassword": "NewPassword1#"
}

### ============================================
### USER ENDPOINTS
### ============================================

### Get All Users
GET {{baseUrl}}/user

### Get Single User
GET {{baseUrl}}/user/9b7a3fa1-6e1c-457d-872b-0b4efedb33e7

### Create User
POST {{baseUrl}}/user
Content-Type: application/json

{
  "name": "John Doe",
  "email": "john@example.com"
}
